### ISSUE TITLE
Field returns html by default, method text() does not exist

### ISSUE THREAD

**Issue by connor-baer** [selvinortiz/craft-plugin-doxter#4]
The [documentation](https://github.com/selvinortiz/craft-plugin-doxter#text) states that the Doxter Model returns the plain text content stored via the field type. It also describes a method `text()` to achieve the same result. 

I just installed Doxter on a Craft 3-beta.10 install. `{{ entry.doxterField }}` returns the formatted HTML, albeit with the tags escaped. Using  `{{ entry.doxterField.text() }}` throws an error: 

```Neither the property "text" nor one of the methods "text()", "gettext()"/"istext()"/"hastext()" or "__call()" exist and have public access in class "selvinortiz\doxter\fields\data\DoxterData".```

After digging around the source code I was able to output the plain text content with `{{ entry.doxterField.getRaw() }}`. Is this the new way of doing it? If so, please update the docs.

**Comment by selvinortiz** [comment]
@connor-baer Thanks for the heads up! We'll update the code or the documentation to address `text()|getRaw()`.

We'll make sure that plain text is returned by default.

Thank you so much for taking the time to open an issued🙏

**Comment by gui-gui** [comment]
@connor-baer The next version of doxter will have `{{ entry.doxterField }}` return parsed html, the same as `{{ entry.doxterField.html }}`. We opted to do it like this, because craft is doing the same.

To get the raw content, you can now do `{{ entry.doxterField.raw }}`.

The documentation will reflect these changes as soon as the next version is released. Hope this clarifies everything.

**Comment by connor-baer** [comment]
@gui-gui Sounds good to me. Thank you for your hard work!

**Comment by connor-baer** [comment]
Thanks for clarifying and implementing this!
